# Generated by Django 5.0.7 on 2025-01-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('LAWYER', 'Lawyer'), ('JUDGE', 'Judge'), ('CITIZEN', 'Citizen')], max_length=20),
        ),
    ]
