# Generated by Django 5.0.7 on 2025-01-30 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_lawyer_bank_account_number_lawyer_bank_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact_type',
        ),
    ]
