# Generated by Django 5.1.3 on 2025-01-23 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('lawyer_email', models.EmailField(max_length=254)),
                ('citizen_email', models.EmailField(max_length=254)),
                ('order_id', models.CharField(max_length=255)),
                ('payment_id', models.CharField(max_length=50)),
                ('signature', models.CharField(max_length=256)),
                ('refund_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=100)),
                ('requested_at', models.DateTimeField(null=True)),
                ('paid_at', models.DateTimeField(null=True)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
        ),
    ]
