# Generated by Django 5.0.7 on 2025-01-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='proceed',
            field=models.BooleanField(default=False),
        ),
    ]
